### ISSUE TITLE
flutter_file_downloader/MethodCallHandlerImpl.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by ajmaltechgentsia** [abdallah-odeh/flutter_files_downloader#8]

**Comment by abdallah-odeh** [comment]
Can you please provide more info about your issue?
logs, device info & your flutter doctor & version info would be helpful

**Comment by khubabcreation** [comment]
downloadFile error: MissingPluginException(No implementation found for method downloadFile on channel com.abdallah.libs/file_downloader)

**Comment by khubabcreation** [comment]
now this error apear ! 
i think you ought to  review  your code ! when i look into the Example* it shows me only a tab_bar code . So Please check your code . On the Other hand when we run our project after getting your package it show this kind of error

**Comment by abdallah-odeh** [comment]
> downloadFile error: MissingPluginException(No implementation found for method downloadFile on channel com.abdallah.libs/file_downloader)

Since this is a plugin (contains native code), you need to do a **Hot restart**, thus, **Hot reload** will give you such error
Can you please try to do a **Hot restart** or kill the app and perform a normal run and tell me the results?

Thank you for helping me making this plugin better & bugs free

**Comment by abdallah-odeh** [comment]
> now this error apear !
> i think you ought to review your code ! when i look into the Example* it shows me only a tab_bar code . So Please check your code . On the Other hand when we run our project after getting your package it show this kind of error

I believe that you mean this warning? I will be working on it this weekend to figure out what is deprecated in the native code, but the example app works fine even when it appears (it did not appear with me every time I performed a run)
![Screen Shot 2023-04-10 at 9 18 08 AM](https://user-images.githubusercontent.com/68509938/230839404-23520c44-7f2a-4997-8fbb-4ee17fd30cf1.png)

also for the second issue you have, 
> i think you ought to review your code ! when i look into the Example* it shows me only a tab_bar code . So Please check your code .
did you try to run it and it gave you blank screen? It is indeed a Tabbar because it contains **[SettingsTab, SingleDownload, Bulk download]**, also I tried to download it and run it on a different machine and it worked as intended.
Please try to download the example code & run it, and if the issue persists, provide logs, your flutter version & preferably the device type you tried the code on

Thank you again

**Comment by Ajoz101** [comment]
Hi I use this package just fine in my flutter app, but I have faced an issue, whenever I cancel a download, the app crashes every time, So can you please provide me with a proper solution... Thanks in advance

**Comment by abdallah-odeh** [comment]
@Ajoz101 Oh, didn't test that!
I'll investigate that today and let you know the results

**Comment by abdallah-odeh** [comment]
@Ajoz101 
The bug is now solved, please test it out on version [flutter_file_downloader: ^1.1.2](https://pub.dev/packages/flutter_file_downloader)
if you encountered any issue please let me know

**Comment by Ajoz101** [comment]
@abdallah-odeh  
Thank you so Much! I tested the new version and the bug is now solved ✔️👏
Keep on the great progress 👏

**Comment by abdallah-odeh** [comment]
@Ajoz101 
That's great to hear,
thank for helping in making this plugin better.

**Comment by HitogiriSama** [comment]
Exception java.lang.NullPointerException:
  at com.odehbros.flutter_file_downloader.MethodCallHandlerImpl$1.onProgress (MethodCallHandlerImpl.java)
  at com.odehbros.flutter_file_downloader.core.DownloadTask.lambda$trackDownload$1 (DownloadTask.java)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:145)
  at android.app.ActivityThread.main (ActivityThread.java:6145)
  at java.lang.reflect.Method.invoke
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1399)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1194)

**Comment by amdkholil** [comment]
hallo @abdallah-odeh 

I am using the latest version, but I still encounter this issue :
![image](https://github.com/abdallah-odeh/flutter_file_downloader/assets/29882551/22f7b6cc-9974-4d5d-a39b-3f58ff9b63ee)

The application still runs well on my device, but there are concerns that it won't work properly on other devices

thanks for the update

**Comment by Memighty-Utsav** [comment]
downloadFile error: PlatformException(error, Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
